### ISSUE TITLE
Convert predicate<T> to javax.persistence.criteria.CriteriaQuery.expression

### ISSUE THREAD

**Issue by ciprianofernandes** [TrigerSoft/jaque#10]
Can you help me explaining me how to convert

pet -> pet.getColor() == null

to

pet.get(Pet_.color).isNull()

using your library.

Regards

**Comment by kostat** [comment]
Dear @ciprianofernandes, this interface is intended for opening product issues and not for usage questions. Please do not abuse it, in case you have a question you may ask it through convenient channels, like stackoverflow.
Since this is a open source project and I contribute to it in my spare time, I do not provide assistance to commercial projects, only to selected OS projects.
Yet, this project implements LINQ expression trees, therefore the design guidelines used for implementing custom LINQ providers are applicable here, you may search for "writing custom linq provider" in Google and then look for code that deals with the expression tree. Please also note that writing such a provider requires some advanced knowledge in the area of compilation and language design in general since in fact you try to transform one language to another (unless your problem is very narrow). Hope this helps.

**Comment by ciprianofernandes** [comment]
Thank you.
